### ISSUE TITLE
Running doubts

### ISSUE THREAD

**Issue by syf980302** [islambarakat99/Multi-Robot-Formation-Control-using-Deep-Reinforcement-Learning#3]
Hello, I'm very interested in the formation control of multi-agent. I saw your project on github and tried to run it myself, but I have a question for your help.
<img width="866" alt="image" src="https://user-images.githubusercontent.com/90589465/200272921-876a21d0-22b0-4aa4-8125-f008bde185ed.png">

**Comment by islambarakat99** [comment]
It says that the file system can't load `/home/islam/training/policy/` because it doesn't exist, as this line was hard-coded to save the data in a specific directory on my machine, which were used for other purposes that were not related to the project.

In "train.py" you can see in Line 27 
```
parser.add_argument("--save-dir", type=str, default="/home/islam/training/policy/", help="directory in which training state and model should be saved")
```

so here you have to give it your saving directory on your machine

and in lines 35 - 36:
```
parser.add_argument("--benchmark-dir", type=str, default="/home/islam/training/benchmark/", help="directory where benchmark data is saved")
parser.add_argument("--plots-dir", type=str, default="/home/islam/training/curves/", help="directory where plot data is saved")
```

In these lines you have to give it the directories for saving Benchmark Data, Plot Data too

**Comment by syf980302** [comment]
ok, thank you. I see what you mean. Thank you for your help.
